<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="THs-MacBook-Pro.local" failures="0" tests="8" name="test.EventTestCases" time="4.983" errors="1" timestamp="2023-11-20T11:24:05 IST" skipped="3">
  <testcase classname="test.EventTestCases" name="testCreateEvent" time="0.710"/>
  <testcase classname="test.EventTestCases" name="testUpdateEvent" time="0.693"/>
  <testcase classname="test.EventTestCases" name="testGetEvent" time="0.580"/>
  <testcase classname="test.EventTestCases" name="testListEvents" time="0.604">
    <error message="Cannot invoke &quot;java.util.Map.containsKey(Object)&quot; because the return value of &quot;io.restassured.path.json.JsonPath.getMap(String)&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "java.util.Map.containsKey(Object)" because the return value of "io.restassured.path.json.JsonPath.getMap(String)" is null
at test.EventTestCases.testListEvents(EventTestCases.java:56)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:578)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </error>
  </testcase> <!-- testListEvents -->
  <testcase classname="test.EventTestCases" name="testListEvents" time="0.672">
    <skipped/>
  </testcase> <!-- testListEvents -->
  <testcase classname="test.EventTestCases" name="testListEvents" time="0.611">
    <skipped/>
  </testcase> <!-- testListEvents -->
  <testcase classname="test.EventTestCases" name="testListEvents" time="0.529">
    <skipped/>
  </testcase> <!-- testListEvents -->
  <testcase classname="test.EventTestCases" name="testDeleteEvent" time="0.584"/>
</testsuite> <!-- test.EventTestCases -->
